name: Deploy to Azure - Client

on:
  push:
    branches:
      - release
  workflow_run:
    workflows: ["Build and Push image to Azure - Client"]  
    types:
      - completed

env: 
  AZURE_CONTAINER_REGISTRY: HubssonHackathon.azurecr.io        # Update with your Azure Container Registry name
  AZURE_CONTAINER_APP_NAME: team1-client  # Update with your Azure Container App name
  AZURE_RESOURCE_GROUP: hubsson-arcade-clients-resouce-group-1 # Update with your Azure Resource Group name
  AZURE_LOCATION: northeurope                      # Update with your desired Azure region


jobs:
  create-container-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: HubssonHackathon.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          app-name: ${{ env.AZURE_CONTAINER_APP_NAME }}
          acrName: HubssonHackathon
          containerAppName: ${{ env.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.AZURE_CONTAINER_APP_NAME }}:v1