name: Deploy to Azure - Client

on:
  push:
    branches:
      - nemkecske
  workflow_run:
    workflows: ["Build and Push image to Azure - Client"]  
    types:
      - completed

env: 
  AZURE_CONTAINER_REGISTRY: HubssonHackathon.azurecr.io        # Update with your Azure Container Registry name
  AZURE_CONTAINER_APP_NAME: nemkecske-client  # Update with your Azure Container App name
  AZURE_RESOURCE_GROUP: DefaultResourceGroup-NEU          # Update with your Azure Resource Group name
  AZURE_LOCATION: North Europe                      # Update with your desired Azure region


jobs:
    build-and-deploy-client:
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - name: "Checkout GitHub Action"
              uses: actions/checkout@v2

            - name: "Login via Azure CLI"
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: "Build and push"
              uses: azure/docker-login@v1
              with:
                  login-server: HubssonHackathon.azurecr.io
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - run: |
                  docker build -f Hubsson.Hackathon.Arcade.Client.Dotnet/Hubsson.Hackathon.Arcade.Client.Dotnet/Dockerfile . -t HubssonHackathon.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:v1
                  docker push HubssonHackathon.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:v1

            - name: Azure logout
              run: |
                  az logout
